# This file is *NOT* reloaded automatically when you use 'jekyll serve'.
# If you change this file, please restart the server process.

# see https://jekyllrb.com/docs/continuous-integration/
exclude: [vendor]

# Site settings
title: beta.gouv.fr
email: contact@beta.gouv.fr
description: Nous créons des services publics numériques
baseurl: /
url: https://beta.gouv.fr

collections:
  startup:
    output: true

defaults:
  -
    scope:
      path: ""	# means "all files"
      type: startup	# targets a collection
    values:
      layout: startup
      logo: /img/logo-generique-startup-carre.jpg
  -
    scope:
      path: ""  # means "all files"
      type: posts
    values:
      layout: post
  -
    scope:
      path: ""  # means "all files"
    values:
      layout: default

phases:
  incubation:
    investigation:
      name: investigation
    construction:
      name: construction
    consolidation:
      name: consolidation
    passation:
      name: passation
  endgame:
    success:
      name:
        singular: reprise
        plural: reprises
      description: Le service est opéré de manière pérenne par son repreneur institutionnel.
    retirement:
      name:
        singular: fermée
        plural: fermées
      description: Les évolutions de la technologie, de la réglementation ou des usages ont rendu le service obsolète. Il a été fermé en lien avec les partenaires, les usagers et l'administration qui le portait.
    death:
      name:
        singular: abandonnée
        plural: abandonnées
      description: Le service a été abandonné en cours de construction. L'abandon est expliqué pour capitaliser sur l'expérience accumulée.
