# This file is *NOT* reloaded automatically when you use 'jekyll serve'.
# If you change this file, please restart the server process.

# see https://jekyllrb.com/docs/continuous-integration/
exclude: [rb, bin, vendor, app.json]

# Site settings
title: beta.gouv.fr
email: contact@beta.gouv.fr
description: Nous créons des services publics numériques
description_en: We build digital public services
url: https://beta.gouv.fr
baseurl: ""
twitter_id: 715451644683673601  # more stable than the username

# Plugins
gems:
  - jekyll-redirect-from
  - jekyll-feed

# Default author for blog posts, can be overridden in each post
author:
  name: beta.gouv.fr
  twitter: betaGouv

collections:
  startup:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: ""	# means "all files"
      type: startup	# targets a collection
    values:
      layout: startup
      logo: /img/logo-generique-startup-carre.jpg
  -
    scope:
      path: ""  # means "all files"
      type: posts
    values:
      layout: post
  -
    scope:
      path: ""  # means "all files"
    values:
      layout: default

phases:
  startups_in: startups en
  incubation:
    investigation:
      name: investigation
      description: Un agent public a identifié une friction entre les usagers et l'administration.
    construction:
      name: construction
      description: Une équipe de 2 à 4 personnes a été formée pour tester une proposition de valeur.
    consolidation:
      name: consolidation
      description: Des usagers sont satisfaits du service rendu, on le propose à de nouveaux publics.
    passation:
      name: passation
      description: L'équipe et l'administration porteuse considèrent que le service est viable.
  endgame:
    success:
      name: reprises
      description: Le service est opéré de manière pérenne par son repreneur institutionnel.
    retirement:
      name: fermées
      description: Les évolutions de la technologie, de la réglementation ou des usages ont rendu le service obsolète. Il a été fermé en lien avec les partenaires, les usagers et l'administration qui le portait.
    death:
      name: abandonnées
      description: Le service a été abandonné en cours de construction. L'abandon est expliqué pour capitaliser sur l'expérience accumulée.

phases_en:
  startups_in: startups under
  incubation:
    investigation:
      name: investigation
      description: A civil servant has identified a pain point affecting citizens dealing with government.
    construction:
      name: construction
      description: A team of two to four has been formed to hash out a viable solution.
    consolidation:
      name: consolidation
      description: Initial users are enjoying actual benefits from the service, which expands its reach to new users.
    passation:
      name: handover
      description: The team and the public body responsible for the service are satisfied of its viability.
  endgame:
    success:
      name: live
      description: The service has been fully entrusted to the care of a public sector body.
    retirement:
      name: retired
      description: Changes in technology, regulation or usage have made the service obsolete. It has been shut down by the public body responsible for it.
    death:
      name: abandoned
      description: The service has been discontinued while under construction. A post-mortem has been conducted to extract value from the experiment.

excerpt_separator: <!--more-->
