# This file is *NOT* reloaded automatically when you use 'jekyll serve'.
# If you change this file, please restart the server process.

# see https://jekyllrb.com/docs/continuous-integration/
exclude: [rb, bin, vendor, app.json]
include: ['_pages']

# Site settings
title: beta.gouv.fr
email: contact@beta.gouv.fr
description: Nous créons des services publics numériques
description_en: We build digital public services
url: https://beta.gouv.fr
baseurl: ""
twitter_id: 715451644683673601 # more stable than the username

# Do not publish future dated blog posts / job offers.
# @see https://jekyllrb.com/docs/configuration/
future: false

# Plugins
gems:
  - jekyll-redirect-from

# Default author for blog posts, can be overridden in each post
author:
  name: beta.gouv.fr
  twitter: betaGouv

collections:
  incubator:
    output: true
    permalink: /incubateur/:name.html
  startup:
    output: true
  authors:
    output: true
  jobs:
    output: true
    permalink: /recrutement/:year/:month/:day/:title.html

defaults:
  -
    scope:
      path: ""# means "all files"
      type: startup	# targets a collection
    values:
      layout: startup
  -
    scope:
      path: ""
      type: incubator
    values:
      layout: incubator
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: jobs
    values:
      layout: job

excerpt_separator: <!--more-->

sass:
  style: compressed
