# CircleCI 2.0 configuration file. See <https://circleci.com/docs/2.0/language-ruby/>.
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.1-node-browsers

    steps:
      - checkout

      - run:
          name: Update bundler
          command: gem install bundler

      - run:
          name: Generate Gemlock
          command: bundle lock

      - restore_cache:
          keys:
            - cache-v2-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - cache-v2-{{ arch }}-{{ .Branch }}
            - cache-v2

      - run:
          name: Bundle Install
          command: bundle check || bundle install --path vendor/bundle

      - run:
          name: Install html5validator
          command: |
            sudo apt-get update
            sudo apt-get install -y python3-pip
            pip3 install --user --upgrade html5validator  # will install in $HOME/.local

      - save_cache:
          key: cache-v2-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
            - ~/.local
            - ~/.cache

      - run:
          name: Check authors file name structure (first_name.last_name.md)
          command: |
            if ls content/_authors | grep --line-regexp --invert-match '[a-z_-]\+\.[a-z_-]\+\.md'
            then cat <<EOF
              One or more authors do not have the expected structure.
              Contact a website administrator if your generated author file breaks the validator.
              Notes:
              A dot (.) can only appear as a separator between the first and the last names.
              Dashes in names are kept as-is.
              Spaces are replaced by underscores (_).
            EOF
              exit 1
            fi

      - run:
          name: Check Jekyll configuration
          command: bundle exec jekyll doctor

      - run:
          name: Jekyll build
          command: bundle exec jekyll build

      - run:
          name: Check homepage was compiled
          command: test -s _site/index.html

      - run:
          name: Check HTML common mistakes
          command: bundle exec htmlproofer ./_site --assume-extension --check-html --disable-external --empty-alt-ignore --check-img-http

      - run:
          name: Validate HTML spec compliance
          command: $HOME/.local/bin/html5validator --root _site --ignore 'Element "img" is missing required attribute "src"'

      - run:
          name: Check author metadata
          command: ruby rb/bin/validate rb/schema/authors.yml "content/_authors/*.md"

      - run:
          name: Check startup metadata
          command: ruby rb/bin/validate rb/schema/startups.yml "content/_startups/*.md"

      - run:
          name: Lint JSON API pages
          command: bundle exec jsonlint _site/api/v*/*.json

      - run:
          name: Start server
          command: bundle exec jekyll serve --no-watch --skip-initial-build
          background: true

      - run:
          name: Wait for server to start
          command: |
            while ! curl --silent http://localhost:4000
            do sleep 1
            done

# Permettre la migration plus facilement ; Ã  remettre ASAP
#      - run:
#          name: Check social networks friendliness
#          command: ruby rb/test/opengraph.rb
